name: Keep Server Awake

on:
  schedue:
    - cron: '*/15 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl -s https://an-leabharlann-ghealach.onrender.com/nodes > /dev/null

