name: Keep Server Awake

on:
  push:
    branches:
      - master

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API
        run: curl -s https://an-leabharlann-ghealach.onrender.com/ping > /dev/null
